# Generated by Django 4.0.5 on 2022-09-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0001_squashed_0021_remove_ville_les nom_norm doivent être uniques_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ville',
            name='Les code_insee doivent être uniques.',
        ),
        migrations.AlterField(
            model_name='bug',
            name='importance',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='type_lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.typelieu'),
        ),
        migrations.AlterField(
            model_name='typelieu',
            name='catégorie',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ville',
            name='code_insee',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
