# Generated by Django 4.0.2 on 2022-03-05 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0002_alter_chemin_d_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemin_d',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
