# Generated by Django 4.0.2 on 2022-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0006_alter_chemin_d_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('description', models.TextField()),
                ('comment_reproduire', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
