# Generated by Django 4.0.2 on 2022-06-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0007_amenity_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='code_insee',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='densité',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='géom_texte',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='population',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
