# Generated by Django 4.0.2 on 2022-06-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0008_alter_ville_code_insee_alter_ville_densité_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_osm', models.CharField(max_length=200, unique=True)),
                ('nom_français', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='horaires',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='id_osm',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenity',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenity',
            name='lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenity',
            name='texte_tout',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='tél',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='nom',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='type_amenity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dijk.typeamenity'),
            preserve_default=False,
        ),
    ]
