# Generated by Django 4.0.5 on 2022-07-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0010_amenity_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='rue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dijk.rue'),
        ),
    ]
