# Generated by Django 4.0.5 on 2022-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0011_amenity_rue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='message_d_erreur',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
