# Generated by Django 4.0.5 on 2022-07-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0012_bug_message_d_erreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='importance',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
