# Generated by Django 4.0.5 on 2022-07-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0013_bug_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='message_d_erreur',
            field=models.TextField(blank=True, default=None, null=True),
        ),
 
    ]
