# Generated by Django 4.0.5 on 2022-07-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0014_alter_bug_message_d_erreur_alter_typeamenity_nom_osm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='id_osm',
            field=models.BigIntegerField(unique=True),
        ),
    ]
