# Generated by Django 4.0.5 on 2022-08-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0015_alter_amenity_id_osm'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeamenity',
            name='catégorie',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typeamenity',
            name='nom_osm',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='typeamenity',
            constraint=models.UniqueConstraint(fields=('catégorie', 'nom_osm'), name='Une seule entrée pour chaque (catégorie, nom_osm).'),
        ),
    ]
