# Generated by Django 4.0.5 on 2022-08-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0016_typeamenity_catégorie_alter_typeamenity_nom_osm_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenity',
            new_name='Lieu',
        ),
        migrations.RenameModel(
            old_name='TypeAmenity',
            new_name='TypeLieu',
        ),
    ]
