# Generated by Django 4.0.5 on 2022-09-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0017_rename_amenity_lieu_rename_typeamenity_typelieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='texte_tout',
            new_name='json_initial',
        ),
        migrations.AddField(
            model_name='bug',
            name='contact',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Contact (facultatif) : pour être tenu au courant du traitement de ceci.'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='json_nettoyé',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='comment_reproduire',
            field=models.TextField(verbose_name='Comment obtenir le comportement non souhaité : '),
        ),
        migrations.AlterField(
            model_name='bug',
            name='message_d_erreur',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='(facultatif) Message d’erreur reçu :'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='ville',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dijk.ville'),
        ),
    ]
