# Generated by Django 4.0.5 on 2022-09-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0018_rename_texte_tout_lieu_json_initial_bug_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='type_amenity',
            new_name='type_lieu',
        ),
    ]
