# Generated by Django 4.0.5 on 2022-09-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0019_rename_type_amenity_lieu_type_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='code_insee',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
