# Generated by Django 4.0.5 on 2022-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0020_alter_ville_code_insee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='densité',
        ),
        migrations.AddField(
            model_name='ville',
            name='superficie',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
