# Generated by Django 4.0.5 on 2022-09-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0021_remove_ville_densité_ville_superficie'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ville',
            constraint=models.UniqueConstraint(fields=('nom_norm', 'code_insee'), name='Le couple (nom_norm, code_insee) doit être unique.'),
        ),
    ]
