# Generated by Django 4.0.5 on 2022-09-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0022_ville_le couple (nom_norm, code_insee) doit être unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='code_insee',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
