# Generated by Django 4.0.5 on 2022-09-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0023_alter_ville_code_insee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='arête',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dijk.arête'),
        ),
    ]
