# Generated by Django 4.0.5 on 2022-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0024_lieu_arête'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='rue',
        ),
        migrations.AddField(
            model_name='lieu',
            name='adresse',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
