# Generated by Django 4.0.5 on 2022-10-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0025_remove_lieu_rue_lieu_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache_adresse',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='cache_adresse',
            constraint=models.UniqueConstraint(fields=('adresse', 'ville'), name='Une seule entrée pour chaque (adresse, ville).'),
        ),
    ]
