# Generated by Django 4.0.5 on 2022-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0026_alter_cache_adresse_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arête',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='sommet',
            name='zone',
        ),
        migrations.AddField(
            model_name='arête',
            name='ville',
            field=models.ManyToManyField(to='dijk.zone'),
        ),
        migrations.AddField(
            model_name='sommet',
            name='villes',
            field=models.ManyToManyField(to='dijk.ville'),
        ),
    ]
