# Generated by Django 4.0.5 on 2022-10-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0027_remove_arête_zone_remove_sommet_zone_arête_ville_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arête',
            old_name='ville',
            new_name='villes',
        ),
    ]
