# Generated by Django 4.0.5 on 2022-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0028_rename_ville_arête_villes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arête',
            name='villes',
            field=models.ManyToManyField(to='dijk.ville'),
        ),
    ]
