# Generated by Django 4.0.5 on 2022-11-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0029_alter_arête_villes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbreArête',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borne_sud', models.FloatField()),
                ('borne_ouest', models.FloatField()),
                ('borne_nord', models.FloatField()),
                ('borne_est', models.FloatField()),
                ('père', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fils', to='dijk.arbrearête')),
            ],
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['nom']},
        ),
        migrations.CreateModel(
            name='SegmentArête',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_lon', models.FloatField()),
                ('d_lat', models.FloatField()),
                ('a_lon', models.FloatField()),
                ('a_lat', models.FloatField()),
                ('arête', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dijk.arête')),
                ('feuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='dijk.arbrearête')),
            ],
        ),
    ]
