# Generated by Django 4.0.5 on 2022-12-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0030_arbrearête_alter_zone_options_segmentarête'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='arbre_arêtes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dijk.arbrearête'),
        ),
        migrations.AlterField(
            model_name='arbrearête',
            name='père',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_manager_fils', to='dijk.arbrearête'),
        ),
        migrations.AlterField(
            model_name='segmentarête',
            name='arête',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='dijk.arête'),
        ),
        migrations.AlterField(
            model_name='segmentarête',
            name='feuille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_manager_segment', to='dijk.arbrearête'),
        ),
    ]
