# Generated by Django 4.0.5 on 2022-12-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0031_zone_arbre_arêtes_alter_arbrearête_père_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='adresse',
        ),
        migrations.AddField(
            model_name='ville',
            name='lieux_calculés',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='segmentarête',
            name='arête',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='dijk.arête'),
            preserve_default=False,
        ),
    ]
