# Generated by Django 4.0.5 on 2023-01-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0033_groupetypelieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupetypelieu',
            name='féminin',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
