# Generated by Django 4.0.5 on 2023-01-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0035_lieu_nom_norm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='json_initial',
            new_name='json_autres_données',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='json_nettoyé',
        ),
    ]
