# Generated by Django 4.0.5 on 2023-01-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0036_rename_json_initial_lieu_json_autres_données_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='json_autres_données',
            new_name='json_tout',
        ),
    ]
