# Generated by Django 4.0.5 on 2023-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0037_rename_json_autres_données_lieu_json_tout'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='autre_nom',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
