# Generated by Django 4.0.5 on 2023-02-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0039_zone_inclue_dans'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='cycla_max',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='zone',
            name='cycla_min',
            field=models.FloatField(default=1.0),
        ),
    ]
