# Generated by Django 4.0.5 on 2023-10-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0040_zone_cycla_max_zone_cycla_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
