# Generated by Django 5.1.3 on 2024-12-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijk', '0041_lieu_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='sommet',
            name='zones',
            field=models.ManyToManyField(to='dijk.zone'),
        ),
    ]
